<?php
/**
 * Created by PhpStorm.
 * User: aymen
 * Date: 2/21/18
 * Time: 4:48 AM
 */

namespace MainBundle\Repository;
/**
 * AdoptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AdoptionRepository extends \Doctrine\ORM\EntityRepository
{

}