<?php

namespace MainBundle\Repository;

/**
 * AppreciationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppreciationRepository extends \Doctrine\ORM\EntityRepository
{
}
