<?php

namespace MainBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
   /* public function getmostlikedArticle()
    {

        $dql = "select id eventappreciated_id , count(eventappreciated_id)   
                as value_occurence                 
                from appreciation
                where type=1
                group by eventappreciated_id            
                order by value_occurence DESC LIMIT 2;";
        $articles = $this->createQueryBuilder($dql);
                    $results = $articles->getResult();

        return $results;
        }*/
}
