<?php

namespace MainBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBlogByCategory($type)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("blog")
            ->from("MainBundle:Blog", "blog")
            ->leftJoin("blog.categories", "category")
            ->where("category.type = :type")
            ->setParameter("type", $type)
            ->orderBy("blog.id","ASC")
            ->getQuery()
            ->getResult();
    }
}
