<?php
/**
 * Created by PhpStorm.
 * User: aymen
 * Date: 2/21/18
 * Time: 4:46 AM
 */

namespace MainBundle\Repository;
/**
 * BreedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BreedRepository extends \Doctrine\ORM\EntityRepository
{

}