<?php

namespace MainBundle\Repository;

/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends \Doctrine\ORM\EntityRepository
{
}
