<?php

namespace MainBundle\Repository;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends \Doctrine\ORM\EntityRepository
{
}
