<?php

namespace MainBundle\Repository;

/**
 * wishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wishlistRepository extends \Doctrine\ORM\EntityRepository
{
}
